Added chromium note in README about opening pdf links
shivaprsd/doqment pull request #13
Opened 2024-01-02 20:39 UTC by notPlancha

It took me awhile to find out that chromium can just not skip the whole "reading the pdf" part and go straight to downloading them, and it seems some chromium browsers set "download PDFs" on by default (and even turn it on after removing pdf.js for some reason)

Feel free to rewrite the text (or deny the pull request if you think it's not the place), I just think it's useful information and wanted to share

2024-01-07 11:11 UTC, shivaprsd commented
@notPlancha Thanks for being the first ever contributor to *doqment*. 🥇

This is interesting, I never knew that Chrome had such a setting. A note on it is definitely useful, not only in the Readme, but also in the extension listing page in CWS.

I noticed that opening PDF links via the context menu is not affected by this setting (I’m glad that I made that the primary method 😅). But disabling it does break functionality of the toolbar button, opening embedded links, etc.

I think we should make these nuances clear in the note before merging.

2024-01-07 11:25 UTC, shivaprsd requested changes

2024-01-07 11:25 UTC, shivaprsd commented on README.md
> +(Go to *Settings* -> *Site Settings* -> *Additional content settings* if it's there ->
For me, *Site Settings* is under *Settings* -> *Privacy and Security*. Should we add that? Or may be these change between Chrome versions?

2024-01-07 11:25 UTC, shivaprsd commented on README.md
> +should be turned off
When you say “turned off”, you mean the setting should be set to *Download*? Can we make clear why it is so for Edge?

2024-01-07 15:44 UTC, notPlancha commented on README.md
> +(Go to *Settings* -> *Site Settings* -> *Additional content settings* if it's there ->
> For me, Site Settings is under Settings -> Privacy and Security

Is that so? In that case I think it's better to just provide the chrome internal protocol url (chrome://settings/content/pdfDocuments), which *should* be universal

2024-01-07 15:52 UTC, notPlancha commented on README.md
> +(Go to *Settings* -> *Site Settings* -> *Additional content settings* if it's there ->
Nope that0s on me, I forgot that step

2024-01-07 15:56 UTC, notPlancha commented on README.md
> +should be turned off
On edge, instead of having buttons, we have a switch, that's why I was specifying that.
<img width="613" alt="image" src="https://github.com/shivaprsd/doqment/assets/31565873/2de2312a-c7cc-4539-9742-cf517fa89425">

<img width="686" alt="image" src="https://github.com/shivaprsd/doqment/assets/31565873/952af94a-2e6d-46a6-8c5d-10e7f0e46f8e">

2024-01-08 14:55 UTC, shivaprsd commented on README.md
> +should be turned off
I think the label before the switch is clear enough on what it does; so I have removed that.

2024-01-08 14:59 UTC, shivaprsd commented
@notPlancha I have reworded the note. If it looks good to you, can you squash the three commits into one and force push? Thanks! 🙂

2024-01-09 07:52 UTC, merged

2024-01-09 07:56 UTC, shivaprsd commented
@notPlancha The original commit message had a typo, so I edited it.
 
Thanks for the contribution! 🙂 

P.S. when I did the rebase an unrelated commit got into this, no idea how, but doesn't matter. 😅